; =======================================================================
; Strings em PT-BR
; =======================================================================
msgInteger: 
    db "O parametro e inteiro",13
msgString:  
    db "O parametro e string",13
msgSimple:  
    db "O parametro e simples precisao",13
msgDouble:  
    db "O parametro e dupla precisao",13
msgErro:    
    db "Tipo desconhecido",13